language: cpp

env:
  global:
   - secure: "jnFFRLX5m4ex+E+T8mJJDVk5L7HFVOK0oJDyeSrgK9Y2JvIA5O5RXd2IqvueXguPcCYe5dFe3iNHtrmGboQ0rmqZlOeDdp4YId6uTJXTNUf0UL15jHbCFBwflx1faJUXGge0McWzqZg2RZDiEnLVSz64cuSbtvJa+u8A22Prstqai4NgFUl5aoo/DB55IDM2uuN2a/0TOCHylf9Fw/M4xbhZSOEioBhn70bUFZ88nxi5b4X9V4S4FUUGGRwXKQtuRVVWWFGnhnX+Y6WPFqe+bIT+sS2HSAxGRIfJ3a6LdRt7glPVH4tXgxLgyWRrn9ZqhgWK7i2x0GA1b8byOWWE9gWRLwSxQC7UfM/mKqgS61po8no7b1TBc/ghhmEozLUKFzbZT1PZQL/iHa3LQUKLuy/9/XyXoeIQcIFjVkP6vWVJwjRGFr3/46CGaQCuq+Acsb53+YEsXcHIT50hEhy6Si0uNIN9gtLhnEABkwWl9oGssJPXaWUmun8TEGoZygb4NxvczmziZgWIJwNywo9BGhfzfWd5smJhJq0KHLj18bfKreBqp+QkwPEV+Ut+UeEF9h3Tcek63YYfQSNDSpskK5kbXo7rp/o6aLjZDXcDDKp0b5NCRe6wpkIZO8RO5KpmvyonBYCevvHuvPv54oV/BAxaRgysMJSyI4nLmfrDLio="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
          update:
            - true
        coverity_scan:
          project:
            name: "evoplex/evoplex"
            description: "Evoplex is a multi-agent system for networks."
          build_command_prepend: cov-configure --comptype gcc --compiler gcc-4.8 --template && cmake ..
          build_command: make -j5
          branch_pattern: coverity_scan
          notification_email: evoplexmas@gmail.com
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
         - COVERITY_ENABLED=true

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
          update:
            - true
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
          update:
            - true
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
          update:
            - true
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
          update:
            - true
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: osx
      osx_image: xcode7.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

  - if [[ "$TRAVIS_BRANCH" == "coverity_scan" ]]; then
      if [[ -z "$COVERITY_ENABLED" ]]; then
        SKIP_BUILD=true;
      else
        echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ;
      fi;
    fi

  - if [[ -z "$SKIP_BUILD" ]]; then
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        mkdir qt5;
        wget -q -O qt5.9.1.zip https://github.com/evoplex/evoplex-data/releases/download/data/qt5.9.1.zip;
        unzip -qq qt5.9.1.zip -d qt;
        export PATH=`pwd`/qt/5.9.1/gcc_64/bin:$PATH;
        export QT_PLUGIN_PATH=`pwd`/qt/5.9.1/gcc_64/plugins;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update > /dev/null;
        brew upgrade > /dev/null;
        brew install qt;
        export PATH="/usr/local/opt/qt/bin:$PATH";
      fi
    fi

install:
  - if [[ -z "$SKIP_BUILD" ]]; then
      mkdir build && cd build ;
      cmake .. && make -j5 ;
    fi

# before_script:

script:
  - ctest --output-on-failure

#after_success:

notifications:
  email:
    recipients:
      - evoplexmas@gmail.com
    on_success: change
    on_failure: always
